import FadeIn from "@/components/fade-in";
import Hero from "@/components/hero";
import ProjectCard from "@/components/project-card";
import SectionTitle from "@/components/section-title";

export default function Home() {
  return (
    <main className="relative w-full flex flex-col items-center text-zinc-700">
      <div className="absolute top-0 left-0 w-full z-2 overflow-hidden pointer-events-none">
        <svg
          viewBox="0 0 800 400"
          className="w-full min-w-[1000px] max-h-[1250px]"
          preserveAspectRatio="xMidYMid slice"
        >
          <path id="curve" fill="#c2e8f3ff" d="M 800 50 Q 400 100 0 200 L 0 0 L 800 0 L 800 300 Z">
          </path>
        </svg>
      </div >
      <div className="pt-24 w-full">
        <Hero />
        <div
          id="web"
          className="w-full min-h-screen flex flex-col pt-24"
        >
          <div className="mx-auto max-w-[1200px]">
            <div className="min-h-screen">
              <FadeIn className="flex flex-col justify-start items-center">
                <SectionTitle>Web Dev Projects</SectionTitle>
                <ProjectCard
                  title="Wind Balloons"
                  link="https://storage.googleapis.com/wind-map-frontend/index.html"
                  subtitle="Weather balloon and wind visualizer"
                  image="/wind-balloons.png"
                  alt="Screenshot of wind balloons web app"
                  features={["Visualization of balloon positions updated at regular intervals", "Balloon trajectories generated by processing and smoothing data", "Wind particle simulation using bilinear interpolation"]}
                  stack={["WebGL", "HTML", "CSS", "JavaScript", "Windborne Systems API", "NOAA GFS", "Python", "Google Cloud Run", "Google Cloud Storage"]}
                  imageRight={false}
                />
              </FadeIn>
              <FadeIn className="flex flex-col justify-start items-center">
                <ProjectCard
                  title="shop.yoob.space"
                  link="https://shop.yoob.space"
                  subtitle="Full-stack eCommerce web app for custom stickers"
                  image="/sticker-store.png"
                  alt="Screenshot of shop.yoob.space web app"
                  features={["Responsive shopping cart", "Secure checkout with Stripe", "Admin tools to upload products"]}
                  stack={["Next.js", "Tailwind CSS", "Firestore", "Stripe", "Cloudinary", "Docker", "Google Cloud Run"]}
                  imageRight={true}
                />
              </FadeIn>
            </div>
            <div className="min-h-screen pt-24" id="game">
              <FadeIn className="flex flex-col justify-start items-center">
                <SectionTitle>Game Dev Projects</SectionTitle>
                <ProjectCard
                  title="Slime in a Trench Coat"
                  link="https://slimeinatrenchcoat.com/"
                  subtitle="A puzzle mystery game in development"
                  image="/slime_in_a_trench_coat.png"
                  alt="Banner image for Slime in a Trench Coat with Jin and Jel sitting on a bridge."
                  features={["Puzzle and cooking systems", "JSON based dialogue and save systems", "Simple 2D combat"]}
                  stack={["Godot", "C#"]}
                  imageRight={false}
                />
              </FadeIn>
              <FadeIn className="flex flex-col justify-start items-center">
                <ProjectCard
                  title="Feather Friends"
                  link="https://apps.apple.com/ae/app/feather-friends/id6472413062"
                  subtitle="Cute Bird Collector"
                  image="/ff.png"
                  alt="Feather Friends screenshot with various birds visiting the yard."
                  features={["Decorate yard and grow flowers", "Feed and observe birds", "Unity In-App Purchases and Ads"]}
                  stack={["Unity", "C#"]}
                  imageRight={true}
                />
              </FadeIn>
            </div>
          </div>
        </div>
        <div
          id="contact"
          className="w-full min-h-screen flex flex-col md:flex-row justify-center items-center gap-6 p-10"
        >
          <a
            href="mailto:serinstellahan@gmail.com"
            className="flex items-center justify-center w-full md:w-auto gap-2 px-6 py-2 bg-[#4e5d61] hover:bg-[#748b92] backdrop-blur-sm rounded-xl shadow-lg text-lg font-semibold text-white hover:scale-105 transition-all duration-200 "
          >
            Email
          </a>
          <a
            href="https://github.com/SerinHan"
            target="_blank"
            className="flex items-center justify-center w-full md:w-auto gap-2 px-6 py-2 bg-[#4e5d61] hover:bg-[#748b92] backdrop-blur-sm rounded-xl shadow-lg text-lg font-semibold text-white hover:scale-105 transition-all duration-200"
          >
            GitHub
          </a>
          <a
            href="resume.pdf"
            target="_blank"
            className="flex items-center justify-center w-full md:w-auto gap-2 px-6 py-2 bg-[#4e5d61] hover:bg-[#748b92] backdrop-blur-sm rounded-xl shadow-lg text-lg font-semibold text-white hover:scale-105 transition-all duration-200"
          >
            Resume
          </a>
        </div>
      </div>
    </main >
  );
}
