import FadeIn from "@/components/fade-in";
import ProjectCard from "@/components/project-card";
import SectionTitle from "@/components/section-title";

export default function Home() {
  return (
    <main className="w-full flex flex-col items-center bg-[#f6f6ff] text-zinc-700">

      <FadeIn>
        <section
          id="about"
          className="w-full min-h-screen flex flex-col justify-center items-center p-10 bg-gradient-to-b from-[#f6f6ff] via-[#ffffff] to-[#f6f6ff] text-zinc-700"
        >
          <h1 className="text-5xl md:text-6xl font-bold mb-4 text-center">
            Serin Han
          </h1>
          <p className="text-xl md:text-2xl mb-6 text-center text-zinc-600">
            Full-Stack Web & Game Developer
          </p>
          <p className="text-center max-w-xl text-zinc-500 mb-8">
            I create interactive experiences that blend web apps, games, and data-driven tools—intuitive, practical, and fun to use.
          </p>
          <a
            href="#work"
            className="px-6 py-3 bg-violet-400 text-white font-semibold rounded-lg shadow-md hover:bg-violet-500 transition-colors text-center w-full md:w-auto "
          >
            Explore My Work
          </a>
        </section>
      </FadeIn>
      <div
        id="work"
        className="w-full min-h-screen flex flex-col pt-24"
      >
        <div className="mx-auto max-w-[1200px]">
          <div className="min-h-screen">
            <FadeIn className="flex flex-col justify-start items-center">
              <SectionTitle>Web Dev Projects</SectionTitle>
              <ProjectCard
                title="Wind Balloons"
                link="https://storage.googleapis.com/wind-map-frontend/index.html"
                subtitle="Weather balloon and wind visualizer"
                image="/wind-balloons.png"
                alt="Screenshot of wind balloons web app"
                features={["Visualization of balloon positions updated at regular intervals", "Balloon trajectories generated by processing and smoothing data", "Wind particle simulation using bilinear interpolation"]}
                stack={["WebGL", "HTML", "CSS", "JavaScript", "Windborne Systems API", "NOAA GFS", "Python", "Google Cloud Run", "Google Cloud Storage"]}
                imageRight={false}
              />
            </FadeIn>
            <FadeIn className="flex flex-col justify-start items-center">
              <ProjectCard
                title="shop.yoob.space"
                link="https://shop.yoob.space"
                subtitle="Full-stack eCommerce web app for custom stickers"
                image="/sticker-store.png"
                alt="Screenshot of shop.yoob.space web app"
                features={["Responsive shopping cart", "Secure checkout with Stripe", "Admin tools to upload products"]}
                stack={["Next.js", "Tailwind CSS", "Firestore", "Stripe", "Cloudinary", "Docker", "Google Cloud Run"]}
                imageRight={true}
              />
            </FadeIn>
          </div>
          <div className="min-h-screen">

            <FadeIn className="flex flex-col justify-start items-center">
              <SectionTitle>Game Dev Projects</SectionTitle>
              <ProjectCard
                title="Slime in a Trench Coat"
                link="https://slimeinatrenchcoat.com/"
                subtitle="A puzzle mystery game in development"
                image="/slime_in_a_trench_coat.png"
                alt="Banner image for Slime in a Trench Coat with Jin and Jel sitting on a bridge."
                features={["Puzzle and cooking systems", "JSON based dialogue and save systems", "Simple 2D combat"]}
                stack={["Godot", "C#"]}
                imageRight={false}
              />
            </FadeIn>
            <FadeIn className="flex flex-col justify-start items-center">
              <ProjectCard
                title="Feather Friends"
                link="https://apps.apple.com/ae/app/feather-friends/id6472413062"
                subtitle="Cute Bird Collector"
                image="/ff.png"
                alt="Feather Friends screenshot with various birds visiting the yard."
                features={["Decorate yard and grow flowers", "Feed and observe birds", "Unity In-App Purchases and Ads"]}
                stack={["Unity", "C#"]}
                imageRight={true}
              />
            </FadeIn>
          </div>
        </div>
      </div>
      <div
        id="contact"
        className="w-full min-h-screen flex flex-col md:flex-row justify-center items-center gap-6 p-10"
      >
        <a
          href="mailto:serinstellahan@gmail.com"
          className="flex items-center justify-center w-full md:w-auto gap-2 px-6 py-4  bg-violet-400 backdrop-blur-sm rounded-xl shadow-lg text-lg font-semibold text-white hover:bg-violet-500 hover:scale-105 transition-all duration-200 "
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-6 w-6"
            fill="none"
            viewBox="0 0 24 24"
            stroke="currentColor"
            strokeWidth={2}
          >
            <path
              strokeLinecap="round"
              strokeLinejoin="round"
              d="M16 12h2a2 2 0 002-2V6a2 2 0 00-2-2H6a2 2 0 00-2 2v4a2 2 0 002 2h2m4 0v6m0 0H8m4 0h4"
            />
          </svg>
          Email
        </a>
        <a
          href="https://github.com/SerinHan"
          target="_blank"
          rel="noopener noreferrer"
          className="flex items-center justify-center w-full md:w-auto gap-2 px-6 py-4 bg-violet-400 backdrop-blur-sm rounded-xl shadow-lg text-lg font-semibold text-white hover:bg-violet-500 hover:scale-105 transition-all duration-200"
        >
          <svg
            xmlns="http://www.w3.org/2000/svg"
            className="h-6 w-6"
            fill="currentColor"
            viewBox="0 0 24 24"
          >
            <path d="M12 0C5.37 0 0 5.37 0 12a12 12 0 008.21 11.44c.6.11.82-.26.82-.58v-2.17c-3.34.73-4.04-1.61-4.04-1.61-.55-1.4-1.34-1.77-1.34-1.77-1.09-.74.08-.73.08-.73 1.2.09 1.83 1.23 1.83 1.23 1.07 1.84 2.8 1.31 3.49 1 .11-.77.42-1.31.76-1.61-2.66-.3-5.46-1.33-5.46-5.91 0-1.31.47-2.38 1.23-3.22-.12-.3-.53-1.52.12-3.17 0 0 1-.32 3.3 1.23a11.5 11.5 0 016 0c2.3-1.55 3.3-1.23 3.3-1.23.65 1.65.24 2.87.12 3.17.76.84 1.23 1.91 1.23 3.22 0 4.59-2.8 5.61-5.47 5.91.43.37.81 1.1.81 2.22v3.29c0 .32.22.7.82.58A12 12 0 0024 12c0-6.63-5.37-12-12-12z" />
          </svg>
          GitHub
        </a>
      </div>
    </main>
  );
}
